INSERT INTO quote (author, text) VALUES ('Mahatma Gandhi', 'Soyez le changement que vous voulez voir dans le monde.');
INSERT INTO quote (author, text) VALUES ('Winston Churchill', 'Le succès, c’est d’aller d’échec en échec sans perdre son enthousiasme.');
INSERT INTO quote (author, text) VALUES ('Benjamin Franklin', 'Vous pouvez retarder, mais le temps, lui, ne le fera pas.');
INSERT INTO quote (author, text) VALUES ('Vincent Van Gogh', 'Ce qui serait la vie si nous n’avions pas le courage de tenter quoi que ce soit ?');
INSERT INTO quote (author, text) VALUES ('Pablo Picasso', 'Tout ce que vous pouvez imaginer est réel.');
INSERT INTO quote (author, text) VALUES ('Antoine de Saint-Exupéry', 'Fais de ta vie un rêve, et d’un rêve, une réalité.');
INSERT INTO quote (author, text) VALUES ('Friedrich Nietzsche', 'Ce qui ne nous tue pas nous rend plus forts.');
INSERT INTO quote (author, text) VALUES ('Socrate', 'La seule chose que je sais, c’est que je ne sais rien.');
INSERT INTO quote (author, text) VALUES ('Ralph Waldo Emerson', 'N’allez pas là où le chemin peut mener. Allez là où il n’y a pas de chemin et laissez une trace.');
INSERT INTO quote (author, text) VALUES ('Marilyn Monroe', 'L’imperfection est beauté, la folie est génie et il vaut mieux être totalement ridicule que totalement ennuyeux.');
INSERT INTO quote (author, text) VALUES ('Jim Rohn', 'Prenez soin de votre corps. C’est le seul endroit où vous êtes obligé de vivre.');
INSERT INTO quote (author, text) VALUES ('Confucius', 'Celui qui déplace une montagne commence par déplacer de petites pierres.');
INSERT INTO quote (author, text) VALUES ('Blaise Pascal', 'Le cœur a ses raisons que la raison ne connaît point.');
INSERT INTO quote (author, text) VALUES ('Lao Tseu', 'Un voyage de mille lieues commence toujours par un premier pas.');
INSERT INTO quote (author, text) VALUES ('Albert Schweitzer', 'Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès.');